name: CI - Build & Test

on:
  pull_request:
    branches:
      - main
      - master

jobs:
  build-test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout do código
        uses: actions/checkout@v3

      - name: Instalar Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'

      - name: Instalar dependências
        run: npm install

      - name: Rodar testes e cobertura de código
        run: npm run test:cov

      - name: Analisar código com SonarQube
        uses: SonarSource/sonarqube-scan-action@master
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
          SONAR_HOST_URL: 'https://sonarcloud.io'

      - name: Verificar cobertura mínima (80%)
        run: |
          COVERAGE=$(grep -oP '(?<=All files\s*\|\s*)\d+' coverage/lcov-report/index.html | tail -1)
          if [ "$COVERAGE" -lt 80 ]; then
            echo "Cobertura de testes abaixo de 80% ($COVERAGE%)"
            exit 1
          fi
